### ISSUE TITLE
Failures when running "diy" remote VM

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#56]
Hello,

I'm trying to run a build on a fresh CentOS 6.5 remote VM using the "diy" environment, but running into a couple of issues. I've followed the instructions from https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant-VM  , but am getting a couple of different errors:

```
TASK [mysql : Create database user] ********************************************
task path: /Users/andrew/git/OpenConext-deploy/roles/mysql/tasks/main.yml:53
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{databases.users}}'). This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [openconext.dev.cybera.ca]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'apis'"}
```
Looking to see what it could be, it seems that this line is calling the .apis dict attribute: https://github.com/OpenConext/OpenConext-deploy/blob/5c935d1a26345d295e4684b313e762d34f3b979e/group_vars/diy.yml#L21

If I overwrite that line to say:
```
- { name: apisrw, db_name: apis, password: secret }
```

the playbook seems to work fine... Up until this point:
```
TASK [engineblock : Configure EngineBlock] *************************************
task path: /Users/andrew/git/OpenConext-deploy/roles/engineblock/tasks/main.yml:25
<openconext.dev.cybera.ca> ESTABLISH SSH CONNECTION FOR USER: centos
<openconext.dev.cybera.ca> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=30m -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/Users/andrew/.ansible/cp/ansible-ssh-%h-%p-%r -tt openconext.dev.cybera.ca '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1459458500.26-234043826416806 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1459458500.26-234043826416806 `" )'"'"''
failed: [openconext.dev.cybera.ca] => (item=engineblock.ini) => {"failed": true, "invocation": {"module_args": {"dest": "/etc/openconext/engineblock.ini", "src": "engineblock.ini.j2"}, "module_name": "template"}, "item": "engineblock.ini", "msg": "AnsibleUndefinedVariable: 'pdp' is undefined"}
```

If you need any additional info, please let me know.

Thanks!

**Comment by baszoetekouw** [comment]
The problem causing the second issue is probably a missing config for the new PDP-component.  The config files for the DIY-environments aren't updates very frequently, so when a new component is introduced en new settings in the group_vars files for production and vm are introduced, they aren't always included in the diy files.

Looking at the diff between group_vars/vm.yml and group_vars/diy.yml, you will probably also see issues having to do with the introduction of the authz, oidc, and metadata-exporter.

I guess the easiest way to work around this, is to use a OpenConext-deploy version from November, for example ad58783b0ac34de03769e8ad51cb57e8f12d9eee
You might (but I'm not entirely sure) need to add these two fixes on top:
- https://github.com/OpenConext/OpenConext-deploy/commit/404326ad40db2490cbfed055fe32eed61185d063#diff-bffb1ec1409f4d2f50709ad76595216b
- https://github.com/OpenConext/OpenConext-deploy/commit/50655d3f66b44324fe7a0804ed169c1c6913ec51#diff-bffb1ec1409f4d2f50709ad76595216b

**Comment by baszoetekouw** [comment]
@surfnet-niels Do we have any ongoing efforts to add a proper install target for non-SURFnet users?

**Comment by surfnet-niels** [comment]
Just to be sure: Following this setup should get you a working setup:
https://github.com/OpenConext/OpenConext-deploy/wiki/Installation-steps-to-deploy-OpenConext-on-a-single-system-other-than-the-Vagrant-VM
